# Multidimensional image processing (`scipy.ndimage`)

In [3]:
from scipy.ndimage import correlate
import numpy as np

correlate(np.arange(10), [1, 2.5])

array([ 0,  2,  6,  9, 13, 16, 20, 23, 27, 30])

In [4]:
correlate(np.arange(10), [1, 2.5], output=np.float64)

array([ 0. ,  2.5,  6. ,  9.5, 13. , 16.5, 20. , 23.5, 27. , 30.5])

In [5]:
footprint = np.array([[0, 1, 0], [1, 1, 1], [0, 1, 0]])
footprint

array([[0, 1, 0],
       [1, 1, 1],
       [0, 1, 0]])

In [6]:
from scipy.ndimage import correlate1d
a = [0, 0, 0, 1, 0, 0, 0]
correlate1d(a, [1, 1, 1])

array([0, 0, 1, 1, 1, 0, 0])

In [7]:
a = [0, 0, 0, 1, 0, 0, 0]
correlate1d(a, [1, 1, 1], origin = -1)

array([0, 1, 1, 1, 0, 0, 0])

In [8]:
a = [0, 0, 1, 1, 1, 0, 0]
correlate1d(a, [-1, 1])               # backward difference

array([ 0,  0,  1,  0,  0, -1,  0])

In [9]:
correlate1d(a, [-1, 1], origin = -1)  # forward difference

array([ 0,  1,  0,  0, -1,  0,  0])

In [10]:
correlate1d(a, [0, -1, 1])

array([ 0,  1,  0,  0, -1,  0,  0])

In [11]:
def d2(input, axis, output, mode, cval):
    return correlate1d(input, [1, -2, 1], axis, output, mode, cval, 0)

a = np.zeros((5, 5))
a[2, 2] = 1
from scipy.ndimage import generic_laplace
generic_laplace(a, d2)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  1., -4.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
def d2(input, axis, output, mode, cval, weights):
    return correlate1d(input, weights, axis, output, mode, cval, 0,)

a = np.zeros((5, 5))
a[2, 2] = 1
generic_laplace(a, d2, extra_arguments = ([1, -2, 1],))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  1., -4.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
generic_laplace(a, d2, extra_keywords = {'weights': [1, -2, 1]})

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  1., -4.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
a = np.zeros((5, 5))
a[2, 2] = 1
from scipy.ndimage import sobel, generic_gradient_magnitude
generic_gradient_magnitude(a, sobel)

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.41421356, 2.        , 1.41421356, 0.        ],
       [0.        , 2.        , 0.        , 2.        , 0.        ],
       [0.        , 1.41421356, 2.        , 1.41421356, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [16]:
a = np.arange(12).reshape(3,4)
correlate1d(a, [1, 2, 3])

array([[ 3,  8, 14, 17],
       [27, 32, 38, 41],
       [51, 56, 62, 65]])

In [17]:
def fnc(iline, oline):
    oline[...] = iline[:-2] + 2 * iline[1:-1] + 3 * iline[2:]

from scipy.ndimage import generic_filter1d
generic_filter1d(a, fnc, 3)

array([[ 3,  8, 14, 17],
       [27, 32, 38, 41],
       [51, 56, 62, 65]])

In [18]:
def fnc(iline, oline, a, b):
    oline[...] = iline[:-2] + a * iline[1:-1] + b * iline[2:]

generic_filter1d(a, fnc, 3, extra_arguments = (2, 3))

array([[ 3,  8, 14, 17],
       [27, 32, 38, 41],
       [51, 56, 62, 65]])

In [19]:
generic_filter1d(a, fnc, 3, extra_keywords = {'a':2, 'b':3})

array([[ 3,  8, 14, 17],
       [27, 32, 38, 41],
       [51, 56, 62, 65]])

In [20]:
a = np.arange(12).reshape(3,4)
correlate(a, [[1, 0], [0, 3]])

array([[ 0,  3,  7, 11],
       [12, 15, 19, 23],
       [28, 31, 35, 39]])

In [21]:
def fnc(buffer):
    return (buffer * np.array([1, 3])).sum()

from scipy.ndimage import generic_filter
generic_filter(a, fnc, footprint = [[1, 0], [0, 1]])

array([[ 0,  3,  7, 11],
       [12, 15, 19, 23],
       [28, 31, 35, 39]])

In [22]:
def fnc(buffer, weights):
    weights = np.asarray(weights)
    return (buffer * weights).sum()

generic_filter(a, fnc, footprint = [[1, 0], [0, 1]], extra_arguments = ([1, 3],))

array([[ 0,  3,  7, 11],
       [12, 15, 19, 23],
       [28, 31, 35, 39]])

In [23]:
generic_filter(a, fnc, footprint = [[1, 0], [0, 1]], extra_keywords= {'weights': [1, 3]})

array([[ 0,  3,  7, 11],
       [12, 15, 19, 23],
       [28, 31, 35, 39]])

In [24]:
a = np.arange(12).reshape(3,4)

class fnc_class:
    def __init__(self, shape):
        # store the shape:
        self.shape = shape
        # initialize the coordinates:
        self.coordinates = [0] * len(shape)

    def filter(self, buffer):
        result = (buffer * np.array([1, 3])).sum()
        print(self.coordinates)
        # calculate the next coordinates:
        axes = list(range(len(self.shape)))
        axes.reverse()
        for jj in axes:
            if self.coordinates[jj] < self.shape[jj] - 1:
                self.coordinates[jj] += 1
                break
            else:
                self.coordinates[jj] = 0
        return result

fnc = fnc_class(shape = (3,4))
generic_filter(a, fnc.filter, footprint = [[1, 0], [0, 1]])

[0, 0]
[0, 1]
[0, 2]
[0, 3]
[1, 0]
[1, 1]
[1, 2]
[1, 3]
[2, 0]
[2, 1]
[2, 2]
[2, 3]


array([[ 0,  3,  7, 11],
       [12, 15, 19, 23],
       [28, 31, 35, 39]])

In [25]:
a = np.arange(12).reshape(3,4)

class fnc1d_class:
    def __init__(self, shape, axis = -1):
        # store the filter axis:
        self.axis = axis
        # store the shape:
        self.shape = shape
        # initialize the coordinates:
        self.coordinates = [0] * len(shape)

    def filter(self, iline, oline):
        oline[...] = iline[:-2] + 2 * iline[1:-1] + 3 * iline[2:]
        print(self.coordinates)
        # calculate the next coordinates:
        axes = list(range(len(self.shape)))
        # skip the filter axis:
        del axes[self.axis]
        axes.reverse()
        for jj in axes:
            if self.coordinates[jj] < self.shape[jj] - 1:
                self.coordinates[jj] += 1
                break
            else:
                self.coordinates[jj] = 0

fnc = fnc1d_class(shape = (3,4))
generic_filter1d(a, fnc.filter, 3)

[0, 0]
[1, 0]
[2, 0]


array([[ 3,  8, 14, 17],
       [27, 32, 38, 41],
       [51, 56, 62, 65]])

In [26]:
a = np.arange(12).reshape(4,3).astype(np.float64)
def shift_func(output_coordinates):
    return (output_coordinates[0] - 0.5, output_coordinates[1] - 0.5)

from scipy.ndimage import geometric_transform
geometric_transform(a, shift_func)

array([[0.    , 0.    , 0.    ],
       [0.    , 1.3625, 2.7375],
       [0.    , 4.8125, 6.1875],
       [0.    , 8.2625, 9.6375]])

In [27]:
def shift_func(output_coordinates, s0, s1):
    return (output_coordinates[0] - s0, output_coordinates[1] - s1)

geometric_transform(a, shift_func, extra_arguments = (0.5, 0.5))

array([[0.    , 0.    , 0.    ],
       [0.    , 1.3625, 2.7375],
       [0.    , 4.8125, 6.1875],
       [0.    , 8.2625, 9.6375]])

In [28]:
geometric_transform(a, shift_func, extra_keywords = {'s0': 0.5, 's1': 0.5})

array([[0.    , 0.    , 0.    ],
       [0.    , 1.3625, 2.7375],
       [0.    , 4.8125, 6.1875],
       [0.    , 8.2625, 9.6375]])

In [29]:
a = np.arange(12).reshape(4,3).astype(np.float64)
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [30]:
from scipy.ndimage import map_coordinates
map_coordinates(a, [[0.5, 2], [0.5, 1]])

array([1.3625, 7.    ])

In [31]:
from scipy.ndimage import generate_binary_structure
generate_binary_structure(2, 1)

array([[False,  True, False],
       [ True,  True,  True],
       [False,  True, False]])

In [32]:
generate_binary_structure(2, 2)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [33]:
struct = np.array([[0, 1, 0], [1, 1, 1], [0, 1, 0]])
a = np.array([[1,0,0,0,0], [1,1,0,1,0], [0,0,1,1,0], [0,0,0,0,0]])
a

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [34]:
from scipy.ndimage import binary_dilation
binary_dilation(np.zeros(a.shape), struct, -1, a, border_value=1)

array([[ True, False, False, False, False],
       [ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [35]:
struct = generate_binary_structure(2, 1)
struct

array([[False,  True, False],
       [ True,  True,  True],
       [False,  True, False]])

In [36]:
from scipy.ndimage import iterate_structure
iterate_structure(struct, 2)

array([[False, False,  True, False, False],
       [False,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True, False],
       [False, False,  True, False, False]])

In [37]:
a = np.array([[1,2,2,1,1,0],
              [0,2,3,1,2,0],
              [1,1,1,3,3,2],
              [1,1,1,1,2,1]])
np.where(a > 1, 1, 0)

array([[0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 1, 0]])

In [38]:
a = np.array([[0,1,1,0,0,0],[0,1,1,0,1,0],[0,0,0,1,1,1],[0,0,0,0,1,0]])
s = [[0, 1, 0], [1,1,1], [0,1,0]]
from scipy.ndimage import label
label(a, s)

(array([[0, 1, 1, 0, 0, 0],
        [0, 1, 1, 0, 2, 0],
        [0, 0, 0, 2, 2, 2],
        [0, 0, 0, 0, 2, 0]], dtype=int32), 2)

In [39]:
a = np.array([[0,1,1,0,0,0],[0,1,1,0,1,0],[0,0,0,1,1,1],[0,0,0,0,1,0]])
s = [[1,1,1], [1,1,1], [1,1,1]]
label(a, s)[0]

array([[0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 1, 0]], dtype=int32)

In [40]:
l, n = label([1, 0, 1, 0, 1])
l

array([1, 0, 2, 0, 3], dtype=int32)

In [41]:
l = np.where(l != 2, l, 0)
l

array([1, 0, 0, 0, 3], dtype=int32)

In [42]:
label(l)[0]

array([1, 0, 0, 0, 2], dtype=int32)

In [43]:
input = np.array([[0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 1, 1, 1, 1, 0],
                  [0, 1, 0, 0, 0, 1, 0],
                  [0, 1, 0, 0, 0, 1, 0],
                  [0, 1, 0, 0, 0, 1, 0],
                  [0, 1, 1, 1, 1, 1, 0],
                  [0, 0, 0, 0, 0, 0, 0]], np.uint8)
markers = np.array([[1, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 2, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0]], np.int8)
from scipy.ndimage import watershed_ift
watershed_ift(input, markers)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 2, 2, 2, 1, 1],
       [1, 2, 2, 2, 2, 2, 1],
       [1, 2, 2, 2, 2, 2, 1],
       [1, 2, 2, 2, 2, 2, 1],
       [1, 1, 2, 2, 2, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [44]:
markers = np.array([[0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 2, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 1]], np.int8)
watershed_ift(input, markers)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 2, 2, 2, 1, 1],
       [1, 1, 2, 2, 2, 1, 1],
       [1, 1, 2, 2, 2, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [45]:
markers = np.array([[0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 2, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 0, -1]], np.int8)
watershed_ift(input, markers)

array([[-1, -1, -1, -1, -1, -1, -1],
       [-1, -1,  2,  2,  2, -1, -1],
       [-1,  2,  2,  2,  2,  2, -1],
       [-1,  2,  2,  2,  2,  2, -1],
       [-1,  2,  2,  2,  2,  2, -1],
       [-1, -1,  2,  2,  2, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1]], dtype=int8)

In [46]:
watershed_ift(input, markers,
              structure = [[1,1,1], [1,1,1], [1,1,1]])

array([[-1, -1, -1, -1, -1, -1, -1],
       [-1,  2,  2,  2,  2,  2, -1],
       [-1,  2,  2,  2,  2,  2, -1],
       [-1,  2,  2,  2,  2,  2, -1],
       [-1,  2,  2,  2,  2,  2, -1],
       [-1,  2,  2,  2,  2,  2, -1],
       [-1, -1, -1, -1, -1, -1, -1]], dtype=int8)

In [47]:
a = np.array([[0,1,1,0,0,0],[0,1,1,0,1,0],[0,0,0,1,1,1],[0,0,0,0,1,0]])
l, n = label(a)
from scipy.ndimage import find_objects
f = find_objects(l)
a[f[0]]

array([[1, 1],
       [1, 1]])

In [48]:
a[f[1]]

array([[0, 1, 0],
       [1, 1, 1],
       [0, 1, 0]])

In [49]:
from scipy.ndimage import find_objects
find_objects([1, 0, 3, 4], max_label = 3)

[(slice(0, 1, None),), None, (slice(2, 3, None),)]

In [50]:
image = np.arange(4 * 6).reshape(4, 6)
mask = np.array([[0,1,1,0,0,0],[0,1,1,0,1,0],[0,0,0,1,1,1],[0,0,0,0,1,0]])
labels = label(mask)[0]
slices = find_objects(labels)

In [51]:
np.where(labels[slices[1]] == 2, image[slices[1]], 0).sum()

80

In [52]:
from scipy.ndimage import sum as ndi_sum
ndi_sum(image, labels, 2)

80

In [53]:
ndi_sum(image[slices[1]], labels[slices[1]], 2)

80

In [54]:
ndi_sum(image, labels, [0, 2])

array([178.,  80.])